void NuovaPartita ( void );
giocatore * AvviaPartita ( giocatore *, giocatore *, torneo * );
void StampaMirino ( int, int );
void CancellaMirino ( int, int );
void PulisciLogBox ( void );
void ProceduraPosizionamento ( giocatore *, torneo * );
void InizializzaFlotta ( flotta *, settaggi * );
void CreaCalendario ( torneo * );
void StampaSfondoCampo ( void );
void StampaSfondoCampoPosizionamento ( void );
char OttieniCarattere ( listaint, int, int, int );
void StampaQuadranteAttacco ( listaint, int, int, int );
void StampaQuadranteDifesa ( listaint, int, int, int );
void ScriviElementoListaInteri ( listaint, int, int );
int LeggiElementoListaInteri ( listaint, int );
listaint InizializzaListaInteri ( settaggi * );
listaint InserisciInTesta ( listaint , int );
listaint InizializzaLista ( );
int CellaIsolata ( int, int, listaint, int, int );
int CellaValidaPosizionamento ( int, int, int, giocatore *, torneo * );
void PosizionaNave ( int, int *, int *, giocatore *, torneo *, int *, int *, int *, int );
int CellaAdiacente ( int, int, int, int, listaint, int *, int );
int ContaCelleVuote ( int, int, int, int, listaint );
void StampaSchermataAttesa ( giocatore *, giocatore * );
void CelebrazioneVincitoreTorneo ( giocatore *, settaggi * );
void CelebrazioneVincitorePartita ( giocatore *, settaggi * );
void RipristinaFlotta ( flotta * );
void StampaCalendario ( torneo * );
void SalvaPartita ( torneo *, giocatore *, giocatore *, int, int );
int NuovoNome ( torneo *, int );
void DeallocaLista ( listaint );